WITH CTE AS (
    SELECT 
        MATERIAL_NUMBER,
        PO_NUMBER,
        POSTING_DATE,
        ROW_NUMBER() OVER (PARTITION BY MATERIAL_NUMBER ORDER BY POSTING_DATE ASC, PO_NUMBER ASC) AS rn
    FROM ORDER_DATA
    WHERE 
    MOVEMENT_TYPE = 'BLOCK ENTRY'   
)
SELECT 
    ID.MATERIAL_NUMBER,
    SUM(ID.BLOCKED_INVENTORY) AS TOTAL_BLOCKED_STOCK,
    RO.PO_NUMBER AS FIRST_BLOCKED_PO,
    RO.POSTING_DATE AS FIRST_BLOCKED_DATE
FROM INVENTORY_DATA ID
LEFT JOIN CTE RO ON ID.MATERIAL_NUMBER = RO.MATERIAL_NUMBER AND RO.rn = 1 
GROUP BY 
ID.MATERIAL_NUMBER, 
RO.PO_NUMBER, 
RO.POSTING_DATE
ORDER BY 
ID.MATERIAL_NUMBER;
